"""
Report Generator for AEVA evaluation results
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path
import json
import logging

from aeva.core.result import EvaluationResult
from aeva.report.templates import ReportTemplate, HTMLTemplate

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates evaluation reports in various formats

    Features:
    - HTML/Markdown/PDF output
    - Customizable templates
    - Multi-language support
    - Brand customization
    - Chart integration
    """

    def __init__(
        self,
        template: Optional[ReportTemplate] = None,
        language: str = 'zh',
        brand_config: Optional[Dict[str, Any]] = None
    ):
        """
        Initialize report generator

        Args:
            template: Report template to use
            language: Report language ('zh' or 'en')
            brand_config: Brand customization config (logo, colors, etc.)
        """
        self.template = template or HTMLTemplate()
        self.language = language
        self.brand_config = brand_config or self._default_brand_config()

    def _default_brand_config(self) -> Dict[str, Any]:
        """Get default brand configuration"""
        return {
            'name': 'AEVA Platform',
            'logo': None,
            'primary_color': '#2563eb',
            'secondary_color': '#10b981',
            'footer': 'Generated by AEVA - Algorithm Evaluation & Validation Agent'
        }

    def generate(
        self,
        result: EvaluationResult,
        output_path: Optional[str] = None,
        include_charts: bool = True,
        include_details: bool = True
    ) -> str:
        """
        Generate evaluation report

        Args:
            result: Evaluation result to report
            output_path: Path to save report (None = return string only)
            include_charts: Whether to include charts
            include_details: Whether to include detailed metrics

        Returns:
            Report content as string
        """
        logger.info(f"Generating report for {result.model_name}")

        # Build report context
        context = self._build_context(result, include_charts, include_details)

        # Render template
        report_content = self.template.render(context)

        # Save if output path provided
        if output_path:
            self._save_report(report_content, output_path)
            logger.info(f"Report saved to {output_path}")

        return report_content

    def _build_context(
        self,
        result: EvaluationResult,
        include_charts: bool,
        include_details: bool
    ) -> Dict[str, Any]:
        """Build template context from evaluation result"""
        context = {
            'metadata': self._build_metadata(result),
            'summary': self._build_summary(result),
            'metrics': self._build_metrics(result, include_details),
            'gates': self._build_gates_section(result),
            'analysis': self._build_analysis_section(result),
            'recommendations': self._build_recommendations(result),
            'brand': self.brand_config,
            'language': self.language,
            'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }

        if include_charts:
            context['charts'] = self._build_charts_data(result)

        return context

    def _build_metadata(self, result: EvaluationResult) -> Dict[str, Any]:
        """Build metadata section"""
        return {
            'model_name': result.model_name,
            'model_version': getattr(result, 'model_version', 'N/A'),
            'evaluation_id': getattr(result, 'evaluation_id', 'N/A'),
            'benchmark': getattr(result, 'benchmark', 'N/A'),
            'dataset': getattr(result, 'dataset', 'N/A'),
            'timestamp': result.timestamp if hasattr(result, 'timestamp') else datetime.now()
        }

    def _build_summary(self, result: EvaluationResult) -> Dict[str, Any]:
        """Build summary section"""
        metrics = result.metrics if hasattr(result, 'metrics') else {}

        return {
            'overall_status': result.status,
            'key_metrics': {
                'accuracy': metrics.get('accuracy', 0.0),
                'precision': metrics.get('precision', 0.0),
                'recall': metrics.get('recall', 0.0),
                'f1_score': metrics.get('f1_score', 0.0)
            },
            'performance': {
                'inference_time': metrics.get('inference_time_ms', 0),
                'throughput': metrics.get('throughput', 0)
            },
            'gate_passed': getattr(result, 'gate_passed', True),
            'confidence': getattr(result, 'confidence', 0.0)
        }

    def _build_metrics(
        self,
        result: EvaluationResult,
        include_details: bool
    ) -> Dict[str, Any]:
        """Build metrics section"""
        metrics = result.metrics if hasattr(result, 'metrics') else {}

        base_metrics = {
            'classification': {
                'accuracy': metrics.get('accuracy', 0.0),
                'precision': metrics.get('precision', 0.0),
                'recall': metrics.get('recall', 0.0),
                'f1_score': metrics.get('f1_score', 0.0)
            },
            'performance': {
                'inference_time_ms': metrics.get('inference_time_ms', 0),
                'throughput_qps': metrics.get('throughput', 0),
                'latency_p50': metrics.get('latency_p50', 0),
                'latency_p95': metrics.get('latency_p95', 0),
                'latency_p99': metrics.get('latency_p99', 0)
            },
            'resources': {
                'memory_mb': metrics.get('memory_mb', 0),
                'gpu_utilization': metrics.get('gpu_utilization', 0),
                'cpu_utilization': metrics.get('cpu_utilization', 0)
            }
        }

        if include_details:
            base_metrics['detailed'] = {
                'confusion_matrix': metrics.get('confusion_matrix', None),
                'per_class_metrics': metrics.get('per_class_metrics', {}),
                'error_analysis': metrics.get('error_analysis', {})
            }

        return base_metrics

    def _build_gates_section(self, result: EvaluationResult) -> Dict[str, Any]:
        """Build quality gates section"""
        gate_result = getattr(result, 'gate_result', None)

        if not gate_result:
            return {'enabled': False}

        return {
            'enabled': True,
            'overall_passed': gate_result.get('passed', False),
            'gates': gate_result.get('gates', []),
            'blocking_failures': gate_result.get('blocking_failures', [])
        }

    def _build_analysis_section(self, result: EvaluationResult) -> Dict[str, Any]:
        """Build intelligent analysis section"""
        analysis = getattr(result, 'analysis', None)

        if not analysis:
            return {'enabled': False}

        return {
            'enabled': True,
            'summary': analysis.get('summary', ''),
            'root_causes': analysis.get('root_causes', []),
            'severity': analysis.get('severity', 'info'),
            'confidence': analysis.get('confidence', 0.0)
        }

    def _build_recommendations(self, result: EvaluationResult) -> List[Dict[str, Any]]:
        """Build recommendations section"""
        analysis = getattr(result, 'analysis', None)

        if not analysis:
            return []

        return analysis.get('recommendations', [])

    def _build_charts_data(self, result: EvaluationResult) -> Dict[str, Any]:
        """Build chart data for visualization"""
        metrics = result.metrics if hasattr(result, 'metrics') else {}

        return {
            'metrics_radar': {
                'labels': ['Accuracy', 'Precision', 'Recall', 'F1'],
                'data': [
                    metrics.get('accuracy', 0) * 100,
                    metrics.get('precision', 0) * 100,
                    metrics.get('recall', 0) * 100,
                    metrics.get('f1_score', 0) * 100
                ]
            },
            'confusion_matrix': metrics.get('confusion_matrix', None)
        }

    def _save_report(self, content: str, output_path: str) -> None:
        """Save report to file"""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)

    def generate_comparison_report(
        self,
        results: List[EvaluationResult],
        output_path: Optional[str] = None
    ) -> str:
        """
        Generate comparison report for multiple models

        Args:
            results: List of evaluation results to compare
            output_path: Path to save report

        Returns:
            Report content as string
        """
        logger.info(f"Generating comparison report for {len(results)} models")

        context = {
            'report_type': 'comparison',
            'models': [self._build_metadata(r) for r in results],
            'comparison': self._build_comparison_data(results),
            'brand': self.brand_config,
            'language': self.language,
            'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }

        report_content = self.template.render_comparison(context)

        if output_path:
            self._save_report(report_content, output_path)

        return report_content

    def _build_comparison_data(
        self,
        results: List[EvaluationResult]
    ) -> Dict[str, Any]:
        """Build comparison data for multiple models"""
        metrics_comparison = {}

        for result in results:
            model_name = result.model_name
            metrics = result.metrics if hasattr(result, 'metrics') else {}

            metrics_comparison[model_name] = {
                'accuracy': metrics.get('accuracy', 0.0),
                'precision': metrics.get('precision', 0.0),
                'recall': metrics.get('recall', 0.0),
                'f1_score': metrics.get('f1_score', 0.0),
                'inference_time': metrics.get('inference_time_ms', 0),
                'memory': metrics.get('memory_mb', 0)
            }

        return {
            'metrics': metrics_comparison,
            'best_model': self._identify_best_model(metrics_comparison),
            'rankings': self._compute_rankings(metrics_comparison)
        }

    def _identify_best_model(
        self,
        metrics_comparison: Dict[str, Dict[str, float]]
    ) -> Dict[str, str]:
        """Identify best model for each metric"""
        best_model = {}

        metric_names = ['accuracy', 'precision', 'recall', 'f1_score']

        for metric in metric_names:
            values = {
                model: data.get(metric, 0)
                for model, data in metrics_comparison.items()
            }
            if values:
                best_model[metric] = max(values, key=values.get)

        # For performance metrics, lower is better
        perf_metrics = ['inference_time', 'memory']
        for metric in perf_metrics:
            values = {
                model: data.get(metric, float('inf'))
                for model, data in metrics_comparison.items()
            }
            if values:
                best_model[metric] = min(values, key=values.get)

        return best_model

    def _compute_rankings(
        self,
        metrics_comparison: Dict[str, Dict[str, float]]
    ) -> Dict[str, int]:
        """Compute overall rankings for models"""
        # Simple ranking based on average performance
        rankings = {}

        for model, metrics in metrics_comparison.items():
            score = (
                metrics.get('accuracy', 0) +
                metrics.get('precision', 0) +
                metrics.get('recall', 0) +
                metrics.get('f1_score', 0)
            ) / 4
            rankings[model] = score

        # Sort by score
        sorted_models = sorted(rankings.items(), key=lambda x: x[1], reverse=True)

        return {model: idx + 1 for idx, (model, _) in enumerate(sorted_models)}
